#!/usr/bin/env node
'use strict';

const chalk = require('chalk');
const ora = require('ora');

const { findImages, buildImage, pushImage } = require('./util-docker');
const { logInfo, logError } = require('./util-output');

const branchToTag = {
	develop: 'test',
	master: 'latest',
};

const spinner = ora();
const program = async (batch) => {
	spinner.start('Searching docker images');

	const dockerImages = await findImages(batch, ['ci-node', 'serve']);
	const dockerTags = [
		process.env.TRAVIS_COMMIT && process.env.TRAVIS_COMMIT.substring(0, 7),
		process.env.TRAVIS_TAG,
		branchToTag[process.env.BRANCH],
	].filter(name => !!name);

	spinner.stop();
	logInfo(
		chalk`Found {bold ${dockerImages.length} images}`,
		...dockerImages.map(
			(image, index) => chalk`  {dim ${index + 1}. {underline ${image.name}} (${image.versions.length}x)}`
		)
	);

	for (const image of dockerImages) {
		for (const version of image.versions) {
			const identifier = chalk`{bold ${image.name}} #{underline ${version}}`;

			spinner.start(`Building ${identifier}...`);
			await buildImage(image, version);
			spinner.succeed(chalk`Built ${identifier}`);

			for (const tag of dockerTags) {
				const fullTag = tag === 'latest' ? version : `${version}-${tag}`;

				spinner.start(chalk`Pushing ${identifier} with {bold ${fullTag}}...`);
				await pushImage(image, version, fullTag);
				spinner.succeed(chalk`Pushed ${identifier} with {bold ${fullTag}}`);
			}
		}
	}
};

program(process.argv[2])
	.then(status => process.exit(status))
	.catch(error => {
		spinner.stop();
		logError(error);
		process.exit(1);
	});
